CREATE USER nextcloud WITH PASSWORD '';
CREATE DATABASE nextcloud TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE nextcloud OWNER TO nextcloud;
GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;


CREATE USER wikijs WITH PASSWORD '';
CREATE DATABASE wikijs TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE wikijs OWNER TO wikijs;
GRANT ALL PRIVILEGES ON DATABASE wikijs TO wikijs;


CREATE USER gitea WITH PASSWORD '';
CREATE DATABASE gitea TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE gitea OWNER TO gitea;
GRANT ALL PRIVILEGES ON DATABASE gitea TO gitea;


CREATE USER libreoffice WITH PASSWORD '';
CREATE DATABASE libreoffice TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE libreoffice OWNER TO libreoffice;
GRANT ALL PRIVILEGES ON DATABASE libreoffice TO libreoffice;
